api_platform:
    title: FTTH-API-PHOTO
    description: Cette API est conçue pour gérer et récupérer les photos associées à diverses entités. Elle inclut des points de terminaison pour obtenir des photos en fonction des références liées à des commandes internes, des prestations et des interventions. L'API facilite la gestion des ressources visuelles liées aux opérations commerciales et logistiques.
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
#        pagination_enabled: false
    keep_legacy_inflector: false
    use_symfony_listeners: true
    
